### ISSUE TITLE
supports for CLI

### ISSUE THREAD

**Issue by amiiigh** [gildas-lormeau/SingleFileZ#51]
Actually, I did not include the CLI yet because it was not a priority but I guess copying and pasting the /cli/ folder from SingleFile should work. Stay tuned ;)

_Originally posted by @gildas-lormeau in https://github.com/gildas-lormeau/SingleFileZ/issues/12#issuecomment-504706388_

Hi, 

I tried this one and I'm getting an error 
```
./SingleFileZ/cli/single-file https://youtube.com --browser-executable-path=/usr/bin/google-chrome-stable                      
URL: https://youtube.com
Stack: Error: Evaluation failed: TypeError: Cannot read property 'content' of undefined
    at Object.getPageData (<anonymous>:48:53)
    at __puppeteer_evaluation_script__:2:42
    at ExecutionContext._evaluateInternal (/home/amigh/Desktop/q-project/SingleFileZ/cli/node_modules/puppeteer-core/lib/ExecutionContext.js:102:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/amigh/Desktop/q-project/SingleFileZ/cli/node_modules/puppeteer-core/lib/helper.js:94:19)
    at DOMWorld.evaluate (/home/amigh/Desktop/q-project/SingleFileZ/cli/node_modules/puppeteer-core/lib/DOMWorld.js:89:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/home/amigh/Desktop/q-project/SingleFileZ/cli/node_modules/puppeteer-core/lib/helper.js:94:19)
    at Page.evaluate (/home/amigh/Desktop/q-project/SingleFileZ/cli/node_modules/puppeteer-core/lib/Page.js:591:14)
    at Page.<anonymous> (/home/amigh/Desktop/q-project/SingleFileZ/cli/node_modules/puppeteer-core/lib/helper.js:95:27)
    at getPageData (/home/amigh/Desktop/q-project/SingleFileZ/cli/back-ends/puppeteer.js:117:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by gildas-lormeau** [comment]
I was very optimistic or tired when I wrote that comment. There's some work to do to make SingleFileZ run on as a CLI tool...

**Comment by amiiigh** [comment]
Yeah I figured.

Is there a function or something that I could use to convert the HTML file saved with SingleFile to SingleFileZ outputs (HTML zip)?
I really appreciate your help

**Comment by trevormeier** [comment]
Just a vote of support to say I would love to see the CLI implemented!

**Comment by M-Gonzalo** [comment]
Me too! +1 for CLI.

**Comment by gildas-lormeau** [comment]
@amiiigh, @trevormeier, @M-Gonzalo That's implemented
